# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'NavitiaJourney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NavitiaJourney
  pod 'Alamofire', '4.9.0'
end
